/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication29;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shahad
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private Connection connect() {
        String url = "jdbc:mysql://localhost:3306/cinema";
        String user = "root";
        String password = "";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);

        } catch (Exception e) {

        }
        return conn;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(821, 597));
        setMinimumSize(new java.awt.Dimension(821, 597));
        setPreferredSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton2.setText("Sign up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, 30));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 90, 70));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 80, 70));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 150, -1));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 150, -1));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 70));

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 220, 90, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 160, -1));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, 70));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/big.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(821, 597));
        jLabel1.setMinimumSize(new java.awt.Dimension(821, 597));
        jLabel1.setPreferredSize(new java.awt.Dimension(821, 597));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 880, 1330));

        jButton3.setText("sign up");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/big.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 920, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean check(String usern){
        
         String sql = "SELECT username FROM userdata2 WHERE username=?";

        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, usern);
            

            // pstmt.executeUpdate(); 
            ResultSet rs = pstmt.executeQuery();

            
            if (rs.next()) {
                
                return true;

            }
        }catch(Exception e){
            
        }
        
        
        return false;
    }
    
     private boolean check1(String email1){
        
         String sql = "SELECT email FROM userdata2 WHERE email=?";

        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, email1);
            

            // pstmt.executeUpdate(); 
            ResultSet rs = pstmt.executeQuery();

            
            if (rs.next()) {
                
                return true;

            }
        }catch(Exception e){
            
        }
        
        
        return false;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String username = "";
        char[] password;
        String email = "";
        String stringPassword = "";

        boolean u = false;
        boolean em = false;
        boolean p = false;

        //reading the username
        username = jTextField3.getText();
        //check if empty
        if (username.equals("")) {
            jLabel8.setText("*enter username");
        } //if not empty
        else {
            //check minimum length
            if (username.length() > 10) {
                jLabel8.setText("*enter username less than 10 character");
            } else {
                jLabel8.setText("");
                u = true;
            }
        }

        //read password 
        password = jPasswordField2.getPassword();
        //check if empty
        if (password.length == 0) {
            jLabel10.setText("*enter password");
        } // if not empty
        else {
            String passwordExpression = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
            //convert from char to string
            for (int i = 0; i < password.length; i++) {
                stringPassword += password[i];
            }
            //check if the entered password mathes the regular expression
            if (!stringPassword.matches(passwordExpression)) {
                jLabel10.setText("*enter strong password");
            } else {
                jLabel10.setText("");
                p = true;
            }
        }

        //read the email
        email = jTextField5.getText();
        //  if empty
        if (email.equals("")) {
            jLabel9.setText("*enter email");
        } //if not empty
        else {
            String emailExpression = "[a-zA-z0-9].+@.+[a-zA-z]\\.\\w+";
            boolean isMatch = email.matches(emailExpression);
            if (!isMatch) {
                jLabel9.setText("*enter valid email");
            } else {
                jLabel9.setText("");
                em = true;
            }

        }
        if(check(username)){
        JOptionPane.showMessageDialog(null, "The username is already taken","error", JOptionPane.ERROR_MESSAGE);      // TODO add your handling code here:
      return;
        }
        if(check1(email)){
     JOptionPane.showMessageDialog(null, "The email is already taken","error", JOptionPane.ERROR_MESSAGE);      // TODO add your handling code here:
     return;
        }
        
        if (u) {
            if (em) {
                if (p) {

                    String sql = "INSERT INTO userdata2(username,email,password) VALUES(?,?,?)";

                    try (Connection conn = this.connect();
                            PreparedStatement pstmt = conn.prepareStatement(sql)) {

                   

                        pstmt.setString(1, username);
                        pstmt.setString(2, email);
                        pstmt.setString(3, stringPassword);
                        pstmt.executeUpdate();

                        conn.close();
                    //    JOptionPane.showMessageDialog(null, "register is done ","error", JOptionPane.ERROR_MESSAGE);  
                    jTextField3.setText("");
                       jTextField5.setText("");
                       jPasswordField2.setText("");
                       JOptionPane.showMessageDialog(null,"Registration is done ","Alert",JOptionPane.WARNING_MESSAGE);
                       
                       
                    } catch (Exception e) {

                    }

                }
            }
        }

        //    JOptionPane.showMessageDialog(null, "Please fill all the required fields","error", JOptionPane.ERROR_MESSAGE);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:login

        String username;
        char[] password;
        String stringPassword = "";

        username = jTextField1.getText();
        password = jPasswordField1.getPassword();
        for (int i = 0; i < password.length; i++) {
            stringPassword += password[i];
        }

        String sql = "SELECT username, password FROM userdata2 WHERE username=? AND password=?";

        try (Connection conn = this.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, username);
            pstmt.setString(2, stringPassword);

         
            ResultSet rs = pstmt.executeQuery();

           
            if (rs.next()) {
           
                conn.close();

                movieinfo n = new movieinfo(username);
                n.setVisible(true);

            } else {
                String sql2 = "SELECT username, password FROM employee WHERE username=? AND password=?";
                PreparedStatement pstmt2 = conn.prepareStatement(sql2);
                pstmt2.setString(1, username);
                pstmt2.setString(2, stringPassword);
                ResultSet rs2 = pstmt2.executeQuery();
                if (rs2.next()) {
                    conn.close();
                    addmovie n = new addmovie(username);
                    n.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "incorrect passowrd or usename", "error", JOptionPane.ERROR_MESSAGE);
                }

             
            }

            conn.close();

        } catch (Exception e) {
        }

      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
