/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication29;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author shahad
 */
public class movieinfo extends javax.swing.JFrame {
String name1;
String name2;
String name3;
String username;

    /**
     * Creates new form movieinfo
     */

public movieinfo(){
    
}
    public movieinfo(String username) {
        initComponents();
        jButton3.setVisible(false);
        jButton2.setVisible(false);
        jButton1.setVisible(false);
this.username=username;

        try{
              String sql = "SELECT * from movies ";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
               // Statement st = con.createStatement();
                PreparedStatement pstmt = conn.prepareStatement(sql);
               ResultSet rs = pstmt.executeQuery();
           
                 // movie 1
                 while(true){
                if(rs.next()){
                    name1=rs.getString("name");
                    jLabel8.setText(name1);
                    byte[] img = rs.getBytes("Image");
                    
                      ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    jLabel7.setIcon(newImage);
                    jButton3.setVisible(true);

               }
                else break;
                             

                     // movie 2
               if( rs.next()){
                    name2=rs.getString("name");
                    jLabel10.setText(name2);
                     byte[]  img = rs.getBytes("Image");
                    
                     ImageIcon  image = new ImageIcon(img);
                    Image im = image.getImage();
                  Image   myImg = im.getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    jLabel6.setIcon(newImage);
                       jButton2.setVisible(true);

               }
               else break;
                                                 System.out.println("movie 2");

                          // movie 3
               if( rs.next()){
                   name3=rs.getString("name");
                    jLabel9.setText(name3);
                  byte[]   img = rs.getBytes("Image");
                    
                     ImageIcon  image = new ImageIcon(img);
                   Image  im = image.getImage();
                   Image  myImg = im.getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(),Image.SCALE_SMOOTH);
                  ImageIcon   newImage = new ImageIcon(myImg);
                    jLabel4.setIcon(newImage);
                   jButton1.setVisible(true);

               }
               else break;
                 }
                    

    conn.close();
                
                 }catch(Exception ex){
                ex.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(821, 597));
        setMinimumSize(new java.awt.Dimension(821, 597));
        setPreferredSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Untitled-5.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 160, 210));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, 240));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, 20));

        jButton1.setText("info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        jButton2.setText("info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 130, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, 240));

        jButton3.setText("info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 120, 20));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 160, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/big.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -30, 930, 1320));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/big.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -10, 840, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
              String sql = "SELECT * from movies where name=? ";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
               // Statement st = con.createStatement();
                PreparedStatement pstmt = conn.prepareStatement(sql);
                 pstmt.setString(1,name3);
               ResultSet rs = pstmt.executeQuery();
               rs.next();
          String name= rs.getString("name");
                    byte[] img = rs.getBytes("Image");
                    String story= rs.getString("story");
                    String genre=rs.getString("genre");
                    String time=rs.getString("time");
                    int seats=rs.getInt("seats");
        
          conn.close();
         info n=new info(username,name,img, story, genre, time, seats) ;
         n.setVisible(true);
        
         }
         catch(Exception e){
             
         }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try{
              String sql = "SELECT * from movies where name=? ";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
               // Statement st = con.createStatement();
                PreparedStatement pstmt = conn.prepareStatement(sql);
                 pstmt.setString(1,name2);
               ResultSet rs = pstmt.executeQuery();
               rs.next();
          String name= rs.getString("name");
                    byte[] img = rs.getBytes("Image");
                    String story= rs.getString("story");
                    String genre=rs.getString("genre");
                    String time=rs.getString("time");
                    int seats=rs.getInt("seats");
        
          conn.close();
         info n=new info(username,name,img, story, genre, time, seats) ;
         n.setVisible(true);
        
         }
         catch(Exception e){
             
         }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:b1
         try{
              String sql = "SELECT * from movies where name=? ";
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
               // Statement st = con.createStatement();
                PreparedStatement pstmt = conn.prepareStatement(sql);
                 pstmt.setString(1,name1);
               ResultSet rs = pstmt.executeQuery();
               rs.next();
          String name= rs.getString("name");
                    byte[] img = rs.getBytes("Image");
                    String story= rs.getString("story");
                    String genre=rs.getString("genre");
                    String time=rs.getString("time");
                    int seats=rs.getInt("seats");
        
          conn.close();
         info n=new info(username,name,img, story, genre, time, seats) ;
         n.setVisible(true);
        
         }
         catch(Exception e){
             
         }
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        account a=new account(username);
        a.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movieinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movieinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movieinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movieinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
